//! Making sure everything a version needs is on disk before launching.

use std::path::PathBuf;
use std::sync::Arc;

use crate::error::{ErrorKind, LauncherError, Result};
use crate::net::download::{
    dedupe_by_destination, download_all, total_bytes, DownloadItem, ProgressSink,
};
use crate::paths::Paths;
use crate::tasks::Progress;

use super::rules::Features;
use super::version::VersionJson;
use super::{assets, libraries, manifest};

pub struct InstalledVersion {
    pub version: VersionJson,
    pub classpath: Vec<PathBuf>,
    pub natives_dir: PathBuf,
    /// What `--assetsDir` should point at: the shared store, or the
    /// materialised tree for pre-1.7 versions.
    pub assets_dir: PathBuf,
    pub assets_index: String,
}

/// Resolves the profile, downloads whatever is missing and unpacks natives.
///
/// Safe to call before every launch: files that already match their SHA1 are
/// skipped, so a warm instance starts in well under a second.
pub async fn ensure_installed(
    client: &reqwest::Client,
    paths: &Paths,
    instance_id: &str,
    version_id: &str,
    concurrency: usize,
    task: Arc<dyn Progress>,
) -> Result<InstalledVersion> {
    task.set_stage(String::from("Чтение манифеста версий"));
    let manifest = manifest::load_manifest(client, paths, false).await?;
    task.check_cancelled()?;

    task.set_stage(format!("Описание версии {version_id}"));
    let version = manifest::resolve_version(client, paths, &manifest, version_id).await?;
    task.check_cancelled()?;

    let features = Features::default();
    let resolved = libraries::resolve(&version, &paths.libraries(), features)?;

    let mut downloads = resolved.downloads.clone();
    let client_jar = paths.client_jar(&version.id);

    // A loader profile inherits the vanilla client jar, so the download entry
    // is named after the base version rather than the profile id.
    if let Some(artifact) = version
        .downloads
        .as_ref()
        .and_then(|downloads| downloads.client.as_ref())
    {
        downloads.push(
            DownloadItem::new(artifact.url.clone(), client_jar.clone())
                .with_sha1(artifact.sha1.clone())
                .with_size(artifact.size),
        );
    } else if !client_jar.is_file() {
        return Err(LauncherError::new(
            ErrorKind::Instance,
            format!("У версии {version_id} нет ссылки на клиент"),
        ));
    }

    // One library can be listed twice in a version JSON; count and download it
    // once so the byte total matches reality.
    let downloads = dedupe_by_destination(downloads);
    task.begin_phase(
        format!("Библиотеки ({})", downloads.len()),
        Some(total_bytes(&downloads)),
    );
    download_all(
        client,
        downloads,
        concurrency,
        task.token(),
        Arc::clone(&task) as Arc<dyn ProgressSink>,
    )
    .await?;
    task.check_cancelled()?;

    let natives_dir = paths.instance_natives(instance_id);
    if !resolved.natives.is_empty() {
        task.set_stage(String::from("Распаковка нативных библиотек"));
        let natives = resolved.natives.clone();
        let target = natives_dir.clone();
        tokio::task::spawn_blocking(move || libraries::extract_natives(&natives, &target))
            .await
            .map_err(|error| {
                LauncherError::internal("Сбой распаковки нативов")
                    .with_detail(error.to_string())
            })??;
    }
    task.check_cancelled()?;

    let assets_root = paths.assets();
    let assets_index = version.asset_index_id();
    let mut assets_dir = assets_root.clone();

    if let Some(index_ref) = version.asset_index.clone() {
        task.set_stage(String::from("Список ассетов"));
        let index = assets::load_index(client, &assets_root, &index_ref).await?;
        let items = assets::download_items(&index, &assets_root);

        task.begin_phase(
            format!("Ассеты ({})", items.len()),
            Some(total_bytes(&items)),
        );
        download_all(
            client,
            items,
            concurrency,
            task.token(),
            Arc::clone(&task) as Arc<dyn ProgressSink>,
        )
        .await?;
        task.check_cancelled()?;

        if index.virtual_assets || index.map_to_resources {
            task.set_stage(String::from("Раскладка ассетов"));
            let game_dir = paths.instance_game_dir(instance_id);
            if let Some(virtual_dir) =
                assets::materialise_legacy(&index, &assets_root, &assets_index, &game_dir).await?
            {
                assets_dir = virtual_dir;
            }
        }
    }

    let mut classpath = resolved.classpath;
    classpath.push(client_jar);

    // Files with no download URL (embedded in or generated by a Forge
    // installer) are only known to exist if we look. Failing here beats a
    // ClassNotFoundException thirty seconds into the game's start-up.
    if let Some(missing) = classpath.iter().find(|path| !path.is_file()) {
        return Err(LauncherError::new(
            ErrorKind::Loader,
            "Не хватает файла лоадера — переустановите его в настройках сборки",
        )
        .with_detail(missing.display().to_string()));
    }

    Ok(InstalledVersion {
        version,
        classpath,
        natives_dir,
        assets_dir,
        assets_index,
    })
}
